version: "4"
services:
  spark-master:
    image: spark-master:latest
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ../spark/../notebooks:/opt/spark/work-dir/notebooks
       - ../spark/../data:/opt/spark/work-dir/data
       - ../spark/../src:/opt/spark/work-dir/src
    environment:
      - SPARK_LOCAL_IP=spark-master
      - PYTHONPATH=/opt/spark/work-dir/src
  spark-worker:
    image: spark-worker:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
      - PYTHONPATH=/opt/spark/work-dir/src
    volumes:
       - ../spark/../notebooks:/opt/spark/work-dir/notebooks
       - ../spark/../data:/opt/spark/work-dir/data
       - ../spark/../src:/opt/spark/work-dir/src
  spark-notebook:
    image: spark-base:latest
    depends_on:
      - spark-worker
    environment:
      - PYTHONPATH=/opt/spark/work-dir/src
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
       - ../../spark/notebooks:/opt/spark/work-dir/notebooks
       - ../../spark/data:/opt/spark/work-dir/data
       - ../../spark/src:/opt/spark/work-dir/src
